# Generated by Django 2.2.7 on 2020-01-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bubble', '0005_gallery_plots'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery_plots',
            name='myDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gallery_plots',
            name='plotname',
            field=models.CharField(default='NewPlot', max_length=200),
        ),
    ]
