# Generated by Django 2.2.7 on 2020-02-11 16:51

import bubble.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bubble', '0009_graph_data_myscale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery_plots',
            name='myplots',
            field=models.ImageField(blank=True, null=True, upload_to=bubble.models.upload_plots),
        ),
    ]
