# Generated by Django 2.2.7 on 2020-02-20 16:04

import accounts.models
from django.db import migrations
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200219_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=accounts.models.S3PrivateFileField(blank=True, default='default.jpg', null=True, storage=storages.backends.s3boto3.S3Boto3Storage(acl='private'), upload_to=accounts.models.upload_pic),
        ),
    ]
