# Generated by Django 2.2.7 on 2019-12-15 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_filename', models.CharField(default='Your_file_name', max_length=500)),
                ('graph_title', models.CharField(default='Your graph title', max_length=500)),
                ('graph_xlabel', models.CharField(default='x-axis label', max_length=500)),
                ('graph_ylabel', models.CharField(default='y-axis label', max_length=500)),
                ('myX', models.CharField(max_length=500)),
                ('myY', models.CharField(max_length=500)),
                ('myRadius', models.CharField(max_length=500)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
