# Generated by Django 2.2.7 on 2019-12-15 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph_data',
            name='graph_filename',
            field=models.CharField(default='Your_file_name', max_length=500),
        ),
        migrations.AddField(
            model_name='graph_data',
            name='graph_xlabel',
            field=models.CharField(default='x-axis label', max_length=500),
        ),
        migrations.AddField(
            model_name='graph_data',
            name='graph_ylabel',
            field=models.CharField(default='y-axis label', max_length=500),
        ),
        migrations.AddField(
            model_name='graph_data',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='graph_data',
            name='graph_title',
            field=models.CharField(default='Your graph title', max_length=500),
        ),
    ]
