# Generated by Django 2.2.2 on 2019-11-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph_data',
            name='graph_xlabel',
            field=models.CharField(default='x-axis label', max_length=500),
        ),
        migrations.AddField(
            model_name='graph_data',
            name='graph_ylabel',
            field=models.CharField(default='y-axis label', max_length=500),
        ),
    ]
