# Generated by Django 2.2.2 on 2019-09-10 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20190908_1538'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
