# Generated by Django 2.2.7 on 2020-03-10 17:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_auto_20200310_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking_data',
            name='safekey',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tracking_data',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
