# Generated by Django 2.2.7 on 2019-12-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bubble', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph_data',
            name='myDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
