# Generated by Django 2.2.7 on 2019-12-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bubble', '0002_graph_data_mydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph_data',
            name='slug',
            field=models.SlugField(default='new', unique=True),
        ),
    ]
