# Generated by Django 2.2.7 on 2019-12-17 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bubble', '0003_graph_data_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph_data',
            name='slug',
        ),
    ]
