# Generated by Django 2.2.7 on 2020-01-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bubble', '0006_auto_20200113_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery_plots',
            name='myplots',
            field=models.ImageField(blank=True, null=True, upload_to='plots'),
        ),
    ]
