# Generated by Django 2.2.7 on 2020-01-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bubble', '0007_auto_20200114_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph_data',
            name='graph_description',
            field=models.CharField(default='This is what you can see in this graph...', max_length=2000),
        ),
    ]
