# Generated by Django 2.2.7 on 2020-01-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bubble', '0008_graph_data_graph_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph_data',
            name='myScale',
            field=models.FloatField(default=1, max_length=1),
        ),
    ]
